apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-07sv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xaos-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-07sv@sha256:e81252cb0e0e4913d11384f6cf9f4a780a34f7e381e60f52575cc6537248d388
        name: my-nodejs
        resources: {}
status: {}
